/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* define if bool is a built-in type */
#define HAVE_BOOL

/* define if the compiler supports const_cast<> */
#define HAVE_CONST_CAST

/* Define to 1 if you have the declaration of `acosh', and to 0 if you don't.
 */
#define HAVE_DECL_ACOSH 1

/* Define to 1 if you have the declaration of `atanh', and to 0 if you don't.
 */
#define HAVE_DECL_ATANH 1

/* Define to 1 if you have the declaration of `expm1', and to 0 if you don't.
 */
#define HAVE_DECL_EXPM1 1

/* Define to 1 if you have the declaration of `feenableexcept', and to 0 if
   you don't. */
#define HAVE_DECL_FEENABLEEXCEPT 0

/* Define to 1 if you have the declaration of `fesettrapenable', and to 0 if
   you don't. */
#define HAVE_DECL_FESETTRAPENABLE 0

/* Define to 1 if you have the declaration of `finite', and to 0 if you don't.
 */
#define HAVE_DECL_FINITE 0

/* Define to 1 if you have the declaration of `frexp', and to 0 if you don't.
 */
#define HAVE_DECL_FREXP 1

/* Define to 1 if you have the declaration of `hypot', and to 0 if you don't.
 */
#define HAVE_DECL_HYPOT 1

/* Define to 1 if you have the declaration of `isfinite', and to 0 if you
   don't. */
#define HAVE_DECL_ISFINITE 0

/* Define to 1 if you have the declaration of `isinf', and to 0 if you don't.
 */
#define HAVE_DECL_ISINF 0

/* Define to 1 if you have the declaration of `isnan', and to 0 if you don't.
 */
#define HAVE_DECL_ISNAN 1

/* Define to 1 if you have the declaration of `ldexp', and to 0 if you don't.
 */
#define HAVE_DECL_LDEXP 1

/* Define to 1 if you have the declaration of `log1p', and to 0 if you don't.
 */
#define HAVE_DECL_LOG1P 1

/* define if the compiler supports default template parameters */
#define HAVE_DEFAULT_TEMPLATE_PARAMETERS

/* Define if /dev/null exists */
#define HAVE_DEV_NULL 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
#define HAVE_DOPRNT 1

/* define if the compiler supports dynamic_cast<> */
#define HAVE_DYNAMIC_CAST

/* define if the compiler supports exceptions */
#define HAVE_EXCEPTIONS

/* have exi success and failure */
#define HAVE_EXIT_SUCCESS_AND_FAILURE

/* "HAVE_EXTENDED_PRECISION_REGISTERS" */
/* #undef HAVE_EXTENDED_PRECISION_REGISTERS */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `floor' function. */
/* #undef HAVE_FLOOR */

/* "Define this is IEEE comparisons work correctly (e.g. NaN != NaN)" */
#define HAVE_IEEE_COMPARISONS 1

/* "Define this is IEEE denormalized numbers are available" */
#define HAVE_IEEE_DENORMALS 1

/* "Define if you have inline" */
#define HAVE_INLINE 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `iswprint' function. */
#define HAVE_ISWPRINT 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES

/* define if the compiler accepts the new for scoping rules */
#define HAVE_NEW_FOR_SCOPING

/* Define to 1 if you have the `pow' function. */
/* #undef HAVE_POW */

/* "Define this if printf can handle %Lf for long double" */
#define HAVE_PRINTF_LONGDOUBLE 1

/* Define to 1 if the system has the type `ptrdiff_t'. */
#define HAVE_PTRDIFF_T 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `sqrt' function. */
/* #undef HAVE_SQRT */

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* define if the compiler supports Standard Template Library */
#define HAVE_STL

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* "Defined if this is an official release" */
#define RELEASED 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */

#if HAVE_EXTENDED_PRECISION_REGISTERS
#  define GSL_COERCE_DBL(x) (gsl_coerce_double(x))
#else
#  define GSL_COERCE_DBL(x) (x)
#endif

/* Substitute gsl functions for missing system functions */

#if !HAVE_DECL_HYPOT
#  define hypot gsl_hypot
#endif

#if !HAVE_DECL_LOG1P
#  define log1p gsl_log1p
#endif

#if !HAVE_DECL_EXPM1
#  define expm1 gsl_expm1
#endif

#if !HAVE_DECL_ACOSH
#  define acosh gsl_acosh
#endif

#if !HAVE_DECL_ASINH
#  define asinh gsl_asinh
#endif

#if !HAVE_DECL_ATANH
#  define atanh gsl_atanh
#endif

#if !HAVE_DECL_LDEXP
#  define ldexp gsl_ldexp
#endif

#if !HAVE_DECL_FREXP
#  define frexp gsl_frexp
#endif

#if !HAVE_DECL_ISINF
#  define isinf gsl_isinf
#endif

#if !HAVE_DECL_FINITE
#  if HAVE_DECL_ISFINITE
#    define finite isfinite
#  else
#    define finite gsl_finite
#  endif
#endif

#if !HAVE_DECL_ISNAN
#  define isnan gsl_isnan
#endif

#ifdef __GNUC__
#  define DISCARD_POINTER(p) do { ; } while (p ? 0 : 0);
#else
#  define DISCARD_POINTER(p)                      /* ignoring discarded pointer */
#endif

#if defined(GSL_RANGE_CHECK_OFF) || !defined(GSL_RANGE_CHECK)
#  define GSL_RANGE_CHECK 0                       /* turn off range checking by default internally */
#endif
