package:
  name: variant_tools
  version: !!str 3.0.1

source:
  fn: variant_tools-3.0.1.tar.gz
  url: https://pypi.python.org/packages/source/v/variant_tools/variant_tools-3.0.1.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - simupop = simupop:main
    #
    # Would create an entry point called simupop that calls simupop.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python # [py3k]
    - setuptools
    - numpy
    - cython
    - pyzmq

  run:
    - python # [py3k]
    - numpy

test:
  # Python imports
  imports:
    - variant_tools

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://varianttools.sourceforge.net
  license: GNU General Public License (GPL)
  summary: 'Integrated annotation and analysis of next gen sequencing data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
