# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        args: ["--ignore=E501,W504,W503, E128"]
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''
    hooks:
    -   id: yapf
        args: [--style, "{based_on_style:chromium,indent_width:4}"]
